### ISSUE TITLE
Improve simpletest by adding some sample data

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_CircuitPython_FakeRequests#2]
With this being its own library, users are starting to use this, so it would be nice to have users be able to see an example in action.

**Comment by jposada202020** [comment]
@makermelissa could a json example file in the library works, and getting data from it?

**Comment by makermelissa** [comment]
Basically yes, but I was also thinking something a little more substantial than the current example such as something that iterates through the data.
